In [1]:
import sys
sys.path.append('C:/Users/ug033207/dynamic scheduling/dynamic-scheduling/functions')
from generate_results import generate_results
from yeni_model import yeni_model
from weighted_days_model import weighted_days_model
from yeni_model2 import yeni_model2


import random
from pyomo.environ import *
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt
import time
import copy
import math
#random.seed(1)


In [2]:
n = 8

teams = list(range(1,n+1))
days = list((range(1,n)))
print(days)
ratings_list = []
#results_df = pd.read_excel('C:/Users/ug033207/match_resultlar.xlsx', sheet_name= 'Germany second half')
#soln_df = pd.read_excel('C:/Users/ug033207/Bundesliga real result.xlsx', sheet_name= 'solution')

#rastgele maç sonuçları generate eden kodum


[1, 2, 3, 4, 5, 6, 7]


In [3]:
# Burada result matrixi oluşturuyorum.





"""
matrix= np.zeros((10,10) ,dtype=int)
matrix[0, :] = 3  # Fill the first row with 3
matrix[4, :] = 1 # Fill the second row with 1
matrix[7, :] = 3  # Fill the second row with 1
matrix[1, :] = 3
matrix[2, 5:12] = 3
matrix[3, :] = 3
print(np.linalg.det(result_array))
#matrix = np.random.choice([0, 1], size=(10, 10))
data = pd.DataFrame(matrix, columns=teams, index=teams)

print(matrix)

output, d1_df, d2_df, obj_value, l, l2= yeni_model(teams, days, data)
"""

'\nmatrix= np.zeros((10,10) ,dtype=int)\nmatrix[0, :] = 3  # Fill the first row with 3\nmatrix[4, :] = 1 # Fill the second row with 1\nmatrix[7, :] = 3  # Fill the second row with 1\nmatrix[1, :] = 3\nmatrix[2, 5:12] = 3\nmatrix[3, :] = 3\nprint(np.linalg.det(result_array))\n#matrix = np.random.choice([0, 1], size=(10, 10))\ndata = pd.DataFrame(matrix, columns=teams, index=teams)\n\nprint(matrix)\n\noutput, d1_df, d2_df, obj_value, l, l2= yeni_model(teams, days, data)\n'

In [4]:
ratings_list1 = []
for i in range(1,11):
    results_df = generate_results(teams)
    result_array = np.zeros((n, n), dtype=int)
    for _, row in results_df.iterrows():
        result = row['Result']
        team1 = row['Team 1']
        team2 = row['Team 2']

        index_team1 = teams.index(team1)
        index_team2 = teams.index(team2)

        if team1 == result:
            result_array[index_team1, index_team2] = 3
        elif team2 == result:
            result_array[index_team2, index_team1] = 3
        else:
            result_array[index_team1, index_team2] = 1
            result_array[index_team2, index_team1] = 1
    print(result_array)
    data = pd.DataFrame(result_array, columns=teams, index=teams)
    output, d1_df, d2_df, y_df, z_df, obj_value, l, l2= weighted_days_model(teams, days, data)
    output1, d1_df, d2_df, y_df, z_df, obj_value, l, l2= yeni_model(teams, days, data)

    sonuc = np.array(output)
    ratings = {i: 0 for i in teams}
    ratings_snapshot = {i: dict(ratings) for i in teams}  # Save a snapshot of the ratings dictionary



    objective_values = []
    for d in days:

        obj_count =0
        for row in sonuc:
            day,team1,team2 = row
            if d==day:
                obj_count +=(abs(ratings[team1] - ratings[team2]))
                ratings[team1] += result_array[team1-1,team2-1]
                ratings[team2] += result_array[team2-1,team1-1]
        objective_values.append(obj_count)
        if d==6:
            ratings_snapshot = {i: ratings[i] for i in teams}
        
        # Append the snapshot to the list
            ratings_list.append(ratings_snapshot)
        
        
        



            
        
    a = sum(objective_values)
    print(a)

    ratings1 = {i: 0 for i in teams}
    ratings_snapshot1 = {i: dict(ratings1) for i in teams}  # Save a snapshot of the ratings dictionary

    sonuc1 = np.array(output1)
    for d in days:
        obj_count =0
        for row in sonuc1:
            day,team1,team2 = row
            if d==day:
                obj_count +=(abs(ratings1[team1] - ratings1[team2]))
                ratings1[team1] += result_array[team1-1,team2-1]
                ratings1[team2] += result_array[team2-1,team1-1]
        if d==6:
            ratings_snapshot1 = {i: ratings1[i] for i in teams}
        
        # Append the snapshot to the list
            ratings_list1.append(ratings_snapshot1)
    print(obj_value)


[[0 0 1 1 0 1 0 3]
 [3 0 1 3 3 0 0 1]
 [1 1 0 0 0 1 0 0]
 [1 0 3 0 1 1 0 0]
 [3 0 3 1 0 3 1 0]
 [1 3 1 1 0 0 0 1]
 [3 3 3 3 1 3 0 0]
 [0 1 3 3 3 1 3 0]]
0.14285714285714285
0.16666666666666666
0.2
0.25
0.3333333333333333
0.5
1.0
Set parameter Username
Academic license - for non-commercial use only - expires 2024-12-15
Read LP format model from file C:\Users\ug033207\AppData\Local\Temp\tmpq1_qjgyq.pyomo.lp
Reading time = 0.01 seconds
x1: 1456 rows, 980 columns, 9016 nonzeros
Set parameter TimeLimit to value 14400
Gurobi Optimizer version 11.0.0 build v11.0.0rc2 (win64 - Windows 11.0 (22621.2))

CPU model: 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz, instruction set [SSE2|AVX|AVX2|AVX512]
Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

Optimize a model with 1456 rows, 980 columns and 9016 nonzeros
Model fingerprint: 0x2da68737
Variable types: 392 continuous, 588 integer (196 binary)
Coefficient statistics:
  Matrix range     [1e+00, 1e+02]
  Objective rang

In [5]:
ratings_list

[{1: 5, 2: 11, 3: 3, 4: 3, 5: 11, 6: 6, 7: 13, 8: 11},
 {1: 1, 2: 11, 3: 9, 4: 9, 5: 3, 6: 11, 7: 9, 8: 11},
 {1: 4, 2: 3, 3: 8, 4: 11, 5: 10, 6: 12, 7: 13, 8: 3},
 {1: 7, 2: 13, 3: 7, 4: 7, 5: 6, 6: 14, 7: 6, 8: 7},
 {1: 5, 2: 16, 3: 6, 4: 9, 5: 4, 6: 9, 7: 6, 8: 11},
 {1: 6, 2: 10, 3: 6, 4: 10, 5: 11, 6: 8, 7: 8, 8: 6},
 {1: 11, 2: 5, 3: 13, 4: 5, 5: 5, 6: 4, 7: 9, 8: 11},
 {1: 9, 2: 12, 3: 10, 4: 6, 5: 11, 6: 7, 7: 6, 8: 7},
 {1: 10, 2: 14, 3: 5, 4: 4, 5: 10, 6: 6, 7: 5, 8: 11},
 {1: 10, 2: 8, 3: 6, 4: 5, 5: 10, 6: 12, 7: 6, 8: 6}]

In [6]:
ratings_list1

[{1: 5, 2: 11, 3: 2, 4: 5, 5: 11, 6: 6, 7: 13, 8: 11},
 {1: 1, 2: 11, 3: 9, 4: 9, 5: 6, 6: 11, 7: 6, 8: 11},
 {1: 4, 2: 3, 3: 8, 4: 11, 5: 10, 6: 10, 7: 11, 8: 6},
 {1: 7, 2: 10, 3: 10, 4: 4, 5: 7, 6: 14, 7: 7, 8: 7},
 {1: 5, 2: 16, 3: 6, 4: 7, 5: 4, 6: 10, 7: 9, 8: 8},
 {1: 7, 2: 8, 3: 9, 4: 8, 5: 9, 6: 5, 7: 11, 8: 6},
 {1: 11, 2: 5, 3: 13, 4: 5, 5: 5, 6: 4, 7: 9, 8: 11},
 {1: 9, 2: 10, 3: 8, 4: 9, 5: 11, 6: 4, 7: 6, 8: 10},
 {1: 10, 2: 12, 3: 6, 4: 5, 5: 10, 6: 6, 7: 5, 8: 9},
 {1: 10, 2: 6, 3: 5, 4: 8, 5: 10, 6: 10, 7: 9, 8: 5}]

print(asd)
print(len(asd))
partitions = [asd[i:i+9] for i in range(0, len(asd), 9)]
k=[]
# Sum the elements of each partition
sums_of_partitions = [sum(partition) for partition in partitions]

# Print the sums
for i, partition_sum in enumerate(sums_of_partitions, 1):
    print(f"Sum of elements in Partition {i}: {partition_sum}")
    k.append(round(partition_sum,0))
print(k)

In [7]:
print(obj_value)

21.0


In [8]:
print(output)
print(d1_df)
print(d2_df)


   Day Team 1 Team 2
0    1      1      6
1    1      2      5
2    1      3      4
3    1      7      8
4    2      1      7
5    2      2      3
6    2      4      5
7    2      6      8
8    3      1      8
9    3      2      4
10   3      3      6
11   3      5      7
12   4      1      4
13   4      2      8
14   4      3      5
15   4      6      7
16   5      1      3
17   5      2      7
18   5      4      6
19   5      5      8
20   6      1      2
21   6      3      8
22   6      4      7
23   6      5      6
24   7      1      5
25   7      2      6
26   7      3      7
27   7      4      8
   Day Team 1  Value
0    1      1    0.0
1    1      2    0.0
2    1      5    0.0
3    1      6    0.0
4    2      1    0.0
5    2      2    0.0
6    2      3    0.0
7    2      4    0.0
8    3      1    0.0
9    3      2    0.0
10   3      4    0.0
11   3      7    0.0
12   4      1    2.0
13   4      2    0.0
14   4      3    0.0
15   4      5    0.0
16   5      1    0.0
17   5      2

In [9]:
print(l)
print(sum(l))
print(l2)
print(sum(l2))

[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 2.0, 0.0, 0.0, 2.0, 0.0, 0.0, 1.0, 1.0, 4.0, 0.0, 1.0, 1.0, 2.0, 0.0, 1.0, 0.0, 3.0, 0.0, 2.0]
21.0
   Day Team 1 Team 2  y+z  d1+d2
0    1      1      4  0.0    0.0
1    1      2      3  0.0    0.0
2    1      5      7  0.0    0.0
3    1      6      8  0.0    0.0
4    2      1      5  0.0    0.0
5    2      2      8  0.0    0.0
6    2      3      6  0.0    0.0
7    2      4      7  0.0    0.0
8    3      1      3  1.0    1.0
9    3      2      5  2.0    2.0
10   3      4      6  0.0    0.0
11   3      7      8  0.0    0.0
12   4      1      7  2.0    2.0
13   4      2      6  0.0    0.0
14   4      3      4  0.0    0.0
15   4      5      8  1.0    1.0
16   5      1      8  1.0    1.0
17   5      2      4  4.0    4.0
18   5      3      7  0.0    0.0
19   5      5      6  1.0    1.0
20   6      1      2  1.0    1.0
21   6      3      5  2.0    2.0
22   6      4      8  0.0    0.0
23   6      6      7  1.0    1.0
24   7      1      6  0.0    

TypeError: unsupported operand type(s) for +: 'int' and 'str'

In [ ]:
print(obj_value)


346.0


In [ ]:
#path = ('C:/Users/ug033207/Bundesliga 4 hours.xlsx')
with pd.ExcelWriter(path, engine='xlsxwriter') as excel_writer:

# Write each DataFrame to a different sheet
    output.to_excel(excel_writer, sheet_name='solution', index=False)
    d2_df.to_excel(excel_writer, sheet_name='d2', index=False)
    d1_df.to_excel(excel_writer, sheet_name='d1', index=False)
    y_df.to_excel(excel_writer, sheet_name='y', index=False)
    z_df.to_excel(excel_writer, sheet_name='z', index=False)
    l2.to_excel(excel_writer, sheet_name='y+z ve d1+d2 degerleri', index=False)
    data.to_excel(excel_writer, sheet_name='result matrix', index=False)

