In [1]:
import sys
sys.path.append('C:/Users/ug033207/dynamic scheduling/dynamic-scheduling/functions')
from generate_results import generate_results
from yeni_model import yeni_model


import random
from pyomo.environ import *
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt
import time
import copy
import math
random.seed(1)


In [2]:
n = 6

teams = list(range(1,n+1))
days = list(range(1,n))

#results_df = pd.read_excel('C:/Users/ug033207/match_resultlar.xlsx', sheet_name= 'Germany second half')

#rastgele maç sonuçları generate eden kodum
results_df = generate_results(teams)

In [3]:
# Burada result matrixi oluşturuyorum.
result_array = np.zeros((n, n), dtype=int)
for _, row in results_df.iterrows():
    result = row['Result']
    team1 = row['Team 1']
    team2 = row['Team 2']

    index_team1 = teams.index(team1)
    index_team2 = teams.index(team2)

    if team1 == result:
        result_array[index_team1, index_team2] = 3
    elif team2 == result:
        result_array[index_team2, index_team1] = 3
    else:
        result_array[index_team1, index_team2] = 1
        result_array[index_team2, index_team1] = 1
print(result_array)
data = pd.DataFrame(result_array, columns=teams, index=teams)


output, d1_df, d2_df, obj_value, l, l2, l3= yeni_model(teams, days, data)

[[0 3 1 3 0 3]
 [0 0 0 0 0 1]
 [1 3 0 0 3 3]
 [0 3 3 0 0 3]
 [3 3 0 3 0 0]
 [0 1 0 0 3 0]]
Set parameter Username
Academic license - for non-commercial use only - expires 2024-12-15
Read LP format model from file C:\Users\ug033207\AppData\Local\Temp\tmpylhemr51.pyomo.lp
Reading time = 0.02 seconds
x1: 675 rows, 480 columns, 3300 nonzeros
Set parameter MIPFocus to value 2
Set parameter Heuristics to value 1
Gurobi Optimizer version 11.0.0 build v11.0.0rc2 (win64 - Windows 10.0 (19045.2))

CPU model: 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz, instruction set [SSE2|AVX|AVX2|AVX512]
Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

Optimize a model with 675 rows, 480 columns and 3300 nonzeros
Model fingerprint: 0x26440297
Variable types: 150 continuous, 330 integer (180 binary)
Coefficient statistics:
  Matrix range     [1e+00, 1e+03]
  Objective range  [1e+00, 1e+00]
  Bounds range     [1e+00, 1e+00]
  RHS range        [1e+00, 1e+03]
Presolve removed 455 ro

In [4]:
print(output)
print(d1_df)
print(d2_df)


   Day Team 1 Team 2
0    1      1      5
1    1      2      4
2    1      3      6
3    2      1      2
4    2      3      4
5    2      5      6
6    3      1      6
7    3      2      3
8    3      4      5
9    4      1      4
10   4      2      6
11   4      3      5
12   5      1      3
13   5      2      5
14   5      4      6
   Day Team 1  Value
0    1      1    0.0
1    1      2    0.0
2    1      3    0.0
3    2      1    0.0
4    2      3    0.0
5    2      5    3.0
6    3      1    0.0
7    3      2    0.0
8    3      4    3.0
9    4      1    0.0
10   4      2    0.0
11   4      3    0.0
12   5      1    0.0
13   5      2    0.0
14   5      4    2.0
   Day Team 2  Value
0    1      5    0.0
1    1      4    0.0
2    1      6    0.0
3    2      2    0.0
4    2      4    0.0
5    2      6    0.0
6    3      6    0.0
7    3      3    3.0
8    3      5    0.0
9    4      4    0.0
10   4      6    3.0
11   4      5    0.0
12   5      3    0.0
13   5      5    5.0
14   5      6

In [5]:
print(l)
print(sum(l))
print(l2)
print(sum(l2))

[0.0, 0.0, 0.0, 0.0, 0.0, 3.0, 0.0, 3.0, 3.0, 0.0, 3.0, 0.0, 0.0, 5.0, 2.0]
19.0
[0.0, 0.0, 0.0, 0.0, 0.0, 3.0, 0.0, 3.0, 3.0, 0.0, 3.0, 0.0, 0.0, 5.0, 2.0]
19.0


In [6]:
print(obj_value)


19.0


In [7]:
#path = ('C:/Users/ug033207/6 takim.xlsx')
with pd.ExcelWriter(path, engine='xlsxwriter') as excel_writer:

# Write each DataFrame to a different sheet
    output.to_excel(excel_writer, sheet_name='solution', index=False)
    d2_df.to_excel(excel_writer, sheet_name='d2', index=False)
    d1_df.to_excel(excel_writer, sheet_name='d1', index=False)

NameError: name 'path' is not defined