In [1]:
import sys
sys.path.append('C:/Users/PC/Documents/GitHub/Ugur-dynamic-scheduling/functions')
from yeni_model import yeni_model
from weighted_days_model import weighted_days_model
from yeni_model2 import yeni_model2
import vizings_schedule
from generate_results import generate_results


import random
from pyomo.environ import *
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt
import time
import copy
import math
#random.seed(1)

In [2]:
n = 20
teams = list(range(1,n+1))
days = list((range(1,n)))

result_df = pd.read_excel('C:/Users/PC/Documents/GitHub/Ugur-dynamic-scheduling/match_resultlar.xlsx', sheet_name= 'Spain second half')
result_matrix = np.zeros((n, n), dtype=int)


for _, row in result_df.iterrows():
    result = row['Result']
    team1 = row['Team 1']
    team2 = row['Team 2']

    index_team1 = teams.index(team1)
    index_team2 = teams.index(team2)


    if team1 == result:
        result_matrix[index_team1, index_team2] = 3
    elif team2 == result:
        result_matrix[index_team2, index_team1] = 3
    else:
        result_matrix[index_team1, index_team2] = 1
        result_matrix[index_team2, index_team1] = 1

print(result_matrix)

canon_schedule = []
vizing_schedule = []

for each_schedule in range (1,100001):
    canon = vizings_schedule.canonical(n)
    obj_canon= vizings_schedule.calculate_obj_value(n, canon, result_matrix)
    vizing = vizings_schedule.vizing(n)
    obj_vizing = vizings_schedule.calculate_obj_value(n, vizing, result_matrix)
    canon_schedule.append(obj_canon)
    vizing_schedule.append(obj_vizing)

print(min(canon_schedule))
print(min(vizing_schedule))

[[0 0 1 0 3 1 0 1 3 0 3 3 3 3 3 3 3 3 0 0]
 [3 0 3 3 3 3 0 3 0 3 1 3 3 3 0 3 0 0 3 1]
 [1 0 0 1 3 3 3 3 3 3 1 3 3 1 3 0 3 3 3 3]
 [3 0 1 0 0 1 3 3 3 1 3 3 3 3 0 0 3 0 0 3]
 [0 0 0 3 0 1 0 3 1 3 0 0 3 3 3 1 3 1 3 0]
 [1 0 0 1 1 0 1 3 0 1 0 0 0 3 3 3 3 3 3 3]
 [3 3 0 0 3 1 0 0 1 0 3 3 1 3 0 3 3 3 1 1]
 [1 0 0 0 0 0 3 0 3 3 1 0 3 3 3 0 3 1 1 0]
 [0 3 0 0 1 3 1 0 0 0 0 1 0 3 3 3 1 3 0 1]
 [3 0 0 1 0 1 3 0 3 0 0 3 0 1 3 3 0 1 0 0]
 [0 1 1 0 3 3 0 1 3 3 0 3 1 0 1 1 0 1 0 3]
 [0 0 0 0 3 3 0 3 1 0 0 0 3 1 1 3 3 0 1 3]
 [0 0 0 0 0 3 1 0 3 3 1 0 0 1 3 1 1 3 0 3]
 [0 0 1 0 0 0 0 0 0 1 3 1 1 0 0 3 1 3 3 0]
 [0 3 0 3 0 0 3 0 0 0 1 1 0 3 0 1 1 0 1 3]
 [0 0 3 3 1 0 0 3 0 0 1 0 1 0 1 0 0 3 3 0]
 [0 3 0 0 0 0 0 0 1 3 3 0 1 1 1 3 0 0 3 0]
 [0 3 0 3 1 0 0 1 0 1 1 3 0 0 3 0 3 0 0 1]
 [3 0 0 3 0 0 1 1 3 3 3 1 3 0 1 0 0 3 0 0]
 [3 1 0 0 3 0 1 3 1 3 0 0 0 3 0 3 3 1 3 0]]
759
583


In [3]:
output, d1_df, d2_df, y_df, z_df, obj_model, l, l2=yeni_model(teams, days, result_matrix)


Set parameter Username
Academic license - for non-commercial use only - expires 2025-03-08
Read LP format model from file C:\Users\PC\AppData\Local\Temp\tmpr5jns_qh.pyomo.lp
Reading time = 0.26 seconds
x1: 25840 rows, 18050 columns, 802351 nonzeros
Set parameter TimeLimit to value 10000
Gurobi Optimizer version 11.0.0 build v11.0.0rc2 (win64 - Windows 11+.0 (22631.2))

CPU model: 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz, instruction set [SSE2|AVX|AVX2|AVX512]
Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

Optimize a model with 25840 rows, 18050 columns and 802351 nonzeros
Model fingerprint: 0xdb2c1071
Variable types: 7220 continuous, 10830 integer (3610 binary)
Coefficient statistics:
  Matrix range     [1e+00, 1e+02]
  Objective range  [1e+00, 1e+00]
  Bounds range     [1e+00, 1e+00]
  RHS range        [1e+00, 1e+02]
Presolve removed 15010 rows and 760 columns
Presolve time: 1.27s
Presolved: 10830 rows, 17290 columns, 771966 nonzeros
Variable types:

C:\Users/PC/Documents/GitHub/Ugur-dynamic-scheduling/functions\yeni_model.py:166: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  l2 = pd.concat([l2, new_row1.dropna()]).reset_index(drop=True)
C:\Users/PC/Documents/GitHub/Ugur-dynamic-scheduling/functions\yeni_model.py:182: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  d1_df = pd.concat([d1_df, new_row1]).reset_index(drop=True)
C:\Users/PC/Documents/GitHub/Ugur-dynamic-scheduling/functions\yeni_model.py:194: FutureWarning: The behavior of DataFram

In [4]:
print(obj_model)

502.0


In [5]:
data = pd.DataFrame(result_matrix)
path = ('C:\\Users\\PC\\Documents\\GitHub\\Ugur-dynamic-scheduling\\LaLiga 10000sec.xlsx')
with pd.ExcelWriter(path, engine='xlsxwriter') as excel_writer:

# Write each DataFrame to a different sheet
    output.to_excel(excel_writer, sheet_name='solution', index=False)
    d2_df.to_excel(excel_writer, sheet_name='d2', index=False)
    d1_df.to_excel(excel_writer, sheet_name='d1', index=False)
    l2.to_excel(excel_writer, sheet_name='y+z ve d1+d2 degerleri', index=False)
    data.to_excel(excel_writer, sheet_name='result matrix', index=False)