In [1]:
import sys
sys.path.append('C:/Users/PC/Documents/GitHub/Ugur-dynamic-scheduling/functions')
from yeni_model import yeni_model
from weighted_days_model import weighted_days_model
from yeni_model2 import yeni_model2
import vizings_schedule
from generate_results import generate_results


import random
from pyomo.environ import *
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt
import time
import copy
import math
#random.seed(1)

big_list_vizing =[]
big_list_canon = []
big_list_model = []
big_list_wmodel = []

In [2]:
n=14
teams = list(range(1,n+1))
days = list((range(1,n)))


simulation_vizing = []
simulation_canonical = []
simulation_model = []
time_list = []
simulation_wm = []

#time'ı da tutmak gerek bir noktada.

for sim in range(1,4):
    result_df, result_matrix = generate_results(teams)
    start = time.time()
    output, d1_df, d2_df, y_df, z_df, obj_model, l, l2=weighted_days_model(teams, days, result_matrix)
    End = time.time()
    time_list.append(End-start)
    sonuc = np.array(output)
    ratings = {i: 0 for i in teams}
    objective_values = []


    for d in days:
        obj_count =0
        for row in sonuc:
            day,team1,team2 = row
            if d==day:
                obj_count +=(abs(ratings[team1] - ratings[team2]))
                ratings[team1] += result_matrix[team1-1,team2-1]
                ratings[team2] += result_matrix[team2-1,team1-1]
        print(ratings)
        objective_values.append(obj_count)
    a = sum(objective_values)
    simulation_wm.append(a)
    canon_schedule = []
    vizing_schedule = []
    output2, d1_df2, d2_df2, y_df2, z_df2, obj_model2, l2, l22=yeni_model(teams, days, result_matrix)
    simulation_model.append(obj_model2)

    for each_schedule in range (1,10001):
        canon = vizings_schedule.canonical(n)
        obj_canon= vizings_schedule.calculate_obj_value(n, canon, result_matrix)
        vizing = vizings_schedule.vizing(n)
        obj_vizing = vizings_schedule.calculate_obj_value(n, vizing, result_matrix)
        canon_schedule.append(obj_canon)
        vizing_schedule.append(obj_vizing)
    
    simulation_canonical.append(min(canon_schedule))
    simulation_vizing.append(min(vizing_schedule))

simulation_canonical = np.array(simulation_canonical)
simulation_vizing = np.array(simulation_vizing)
simulation_model = np.array(simulation_model)
simulation_wm = np.array(simulation_wm)
time_list = np.array(time_list)

big_list_vizing.append(np.mean(simulation_vizing))
big_list_canon.append(np.mean(simulation_canonical))
big_list_model.append(np.mean(simulation_wm))



data = pd.DataFrame(result_matrix)
"""
path = f'C:\\Users\\PC\\Documents\\GitHub\\Ugur-dynamic-scheduling\\wm_20teams_3000sec_sim_number{sim}.xlsx'
with pd.ExcelWriter(path, engine='xlsxwriter') as excel_writer:

# Write each DataFrame to a different sheet
    output.to_excel(excel_writer, sheet_name='wsolution', index=False)
    l2.to_excel(excel_writer, sheet_name='weighted y+z ve d1+d2 degerleri', index=False)
    data.to_excel(excel_writer, sheet_name='result matrix', index=False)
    output2.to_excel(excel_writer, sheet_name='unw solution', index=False)
    l22.to_excel(excel_writer, sheet_name='unw y+z ve d1+d2 degerleri', index=False)
"""


0.07692307692307693
0.08333333333333333
0.09090909090909091
0.1
0.1111111111111111
0.125
0.14285714285714285
0.16666666666666666
0.2
0.25
0.3333333333333333
0.5
1.0
containing a solution
No optimal solution found.
{1: 3, 2: 1, 3: 0, 4: 3, 5: 3, 6: 1, 7: 1, 8: 1, 9: 1, 10: 0, 11: 1, 12: 1, 13: 1, 14: 0}
{1: 4, 2: 2, 3: 1, 4: 3, 5: 3, 6: 1, 7: 4, 8: 2, 9: 4, 10: 3, 11: 2, 12: 1, 13: 2, 14: 3}
{1: 4, 2: 2, 3: 4, 4: 6, 5: 3, 6: 4, 7: 4, 8: 2, 9: 4, 10: 6, 11: 3, 12: 4, 13: 3, 14: 6}
{1: 7, 2: 5, 3: 5, 4: 6, 5: 3, 6: 7, 7: 4, 8: 3, 9: 7, 10: 6, 11: 6, 12: 5, 13: 4, 14: 6}
{1: 8, 2: 6, 3: 5, 4: 6, 5: 6, 6: 7, 7: 7, 8: 6, 9: 7, 10: 6, 11: 6, 12: 8, 13: 7, 14: 9}
{1: 8, 2: 9, 3: 8, 4: 7, 5: 9, 6: 8, 7: 7, 8: 7, 9: 7, 10: 7, 11: 9, 12: 9, 13: 8, 14: 9}
{1: 9, 2: 10, 3: 9, 4: 10, 5: 9, 6: 9, 7: 10, 8: 8, 9: 8, 10: 10, 11: 9, 12: 10, 13: 8, 14: 10}
{1: 12, 2: 13, 3: 9, 4: 13, 5: 9, 6: 9, 7: 10, 8: 11, 9: 11, 10: 10, 11: 12, 12: 10, 13: 9, 14: 11}
{1: 15, 2: 14, 3: 10, 4: 14, 5: 10, 6: 12, 7: 11, 

C:\Users/PC/Documents/GitHub/Ugur-dynamic-scheduling/functions\weighted_days_model.py:168: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  l2 = pd.concat([l2, new_row1]).reset_index(drop=True)
C:\Users/PC/Documents/GitHub/Ugur-dynamic-scheduling/functions\weighted_days_model.py:183: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  d1_df = pd.concat([d1_df, new_row1]).reset_index(drop=True)
C:\Users/PC/Documents/GitHub/Ugur-dynamic-scheduling/functions\weighted_days_model.py:195: FutureWarning: The be

Set parameter Username
Academic license - for non-commercial use only - expires 2025-03-08
Read LP format model from file C:\Users\PC\AppData\Local\Temp\tmpoa9riizh.pyomo.lp
Reading time = 0.06 seconds
x1: 8554 rows, 5915 columns, 138931 nonzeros
Set parameter TimeLimit to value 800
Gurobi Optimizer version 11.0.0 build v11.0.0rc2 (win64 - Windows 11+.0 (22631.2))

CPU model: 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz, instruction set [SSE2|AVX|AVX2|AVX512]
Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

Optimize a model with 8554 rows, 5915 columns and 138931 nonzeros
Model fingerprint: 0xbc9a11a1
Variable types: 2366 continuous, 3549 integer (1183 binary)
Coefficient statistics:
  Matrix range     [1e+00, 1e+02]
  Objective range  [1e+00, 1e+00]
  Bounds range     [1e+00, 1e+00]
  RHS range        [1e+00, 1e+02]
Presolve removed 5005 rows and 364 columns
Presolve time: 0.33s
Presolved: 3549 rows, 5551 columns, 128776 nonzeros
Variable types: 0 continu

C:\Users/PC/Documents/GitHub/Ugur-dynamic-scheduling/functions\yeni_model.py:166: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  l2 = pd.concat([l2, new_row1.dropna()]).reset_index(drop=True)
C:\Users/PC/Documents/GitHub/Ugur-dynamic-scheduling/functions\yeni_model.py:182: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  d1_df = pd.concat([d1_df, new_row1]).reset_index(drop=True)
C:\Users/PC/Documents/GitHub/Ugur-dynamic-scheduling/functions\yeni_model.py:194: FutureWarning: The behavior of DataFram

0.07692307692307693
0.08333333333333333
0.09090909090909091
0.1
0.1111111111111111
0.125
0.14285714285714285
0.16666666666666666
0.2
0.25
0.3333333333333333
0.5
1.0
containing a solution
No optimal solution found.
{1: 3, 2: 1, 3: 1, 4: 1, 5: 3, 6: 0, 7: 3, 8: 0, 9: 1, 10: 0, 11: 1, 12: 1, 13: 0, 14: 3}
{1: 6, 2: 1, 3: 1, 4: 1, 5: 3, 6: 3, 7: 6, 8: 0, 9: 4, 10: 3, 11: 4, 12: 1, 13: 3, 14: 3}
{1: 7, 2: 4, 3: 4, 4: 2, 5: 3, 6: 4, 7: 7, 8: 3, 9: 4, 10: 3, 11: 7, 12: 2, 13: 3, 14: 4}
{1: 8, 2: 5, 3: 5, 4: 5, 5: 3, 6: 5, 7: 7, 8: 6, 9: 5, 10: 4, 11: 8, 12: 5, 13: 4, 14: 4}
{1: 8, 2: 5, 3: 8, 4: 8, 5: 6, 6: 6, 7: 7, 8: 6, 9: 8, 10: 7, 11: 8, 12: 5, 13: 5, 14: 7}
{1: 9, 2: 8, 3: 9, 4: 8, 5: 6, 6: 6, 7: 8, 8: 9, 9: 9, 10: 8, 11: 9, 12: 6, 13: 8, 14: 8}
{1: 12, 2: 8, 3: 9, 4: 8, 5: 9, 6: 9, 7: 11, 8: 9, 9: 12, 10: 9, 11: 9, 12: 7, 13: 8, 14: 11}
{1: 15, 2: 8, 3: 12, 4: 9, 5: 9, 6: 12, 7: 11, 8: 12, 9: 12, 10: 12, 11: 10, 12: 7, 13: 9, 14: 12}
{1: 18, 2: 8, 3: 12, 4: 12, 5: 12, 6: 12, 7: 14, 8: 1

C:\Users/PC/Documents/GitHub/Ugur-dynamic-scheduling/functions\weighted_days_model.py:168: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  l2 = pd.concat([l2, new_row1]).reset_index(drop=True)
C:\Users/PC/Documents/GitHub/Ugur-dynamic-scheduling/functions\weighted_days_model.py:183: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  d1_df = pd.concat([d1_df, new_row1]).reset_index(drop=True)
C:\Users/PC/Documents/GitHub/Ugur-dynamic-scheduling/functions\weighted_days_model.py:195: FutureWarning: The be

Set parameter Username
Academic license - for non-commercial use only - expires 2025-03-08
Read LP format model from file C:\Users\PC\AppData\Local\Temp\tmpmu4_3dii.pyomo.lp
Reading time = 0.06 seconds
x1: 8554 rows, 5915 columns, 132457 nonzeros
Set parameter TimeLimit to value 800
Gurobi Optimizer version 11.0.0 build v11.0.0rc2 (win64 - Windows 11+.0 (22631.2))

CPU model: 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz, instruction set [SSE2|AVX|AVX2|AVX512]
Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

Optimize a model with 8554 rows, 5915 columns and 132457 nonzeros
Model fingerprint: 0xb4fbffff
Variable types: 2366 continuous, 3549 integer (1183 binary)
Coefficient statistics:
  Matrix range     [1e+00, 1e+02]
  Objective range  [1e+00, 1e+00]
  Bounds range     [1e+00, 1e+00]
  RHS range        [1e+00, 1e+02]
Presolve removed 5005 rows and 364 columns
Presolve time: 0.32s
Presolved: 3549 rows, 5551 columns, 122305 nonzeros
Variable types: 0 continu

C:\Users/PC/Documents/GitHub/Ugur-dynamic-scheduling/functions\yeni_model.py:166: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  l2 = pd.concat([l2, new_row1.dropna()]).reset_index(drop=True)
C:\Users/PC/Documents/GitHub/Ugur-dynamic-scheduling/functions\yeni_model.py:182: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  d1_df = pd.concat([d1_df, new_row1]).reset_index(drop=True)
C:\Users/PC/Documents/GitHub/Ugur-dynamic-scheduling/functions\yeni_model.py:194: FutureWarning: The behavior of DataFram

0.07692307692307693
0.08333333333333333
0.09090909090909091
0.1
0.1111111111111111
0.125
0.14285714285714285
0.16666666666666666
0.2
0.25
0.3333333333333333
0.5
1.0
containing a solution
No optimal solution found.
{1: 1, 2: 0, 3: 0, 4: 0, 5: 1, 6: 0, 7: 1, 8: 3, 9: 0, 10: 1, 11: 3, 12: 3, 13: 3, 14: 3}
{1: 4, 2: 3, 3: 0, 4: 3, 5: 1, 6: 3, 7: 4, 8: 4, 9: 0, 10: 4, 11: 3, 12: 3, 13: 4, 14: 3}
{1: 5, 2: 3, 3: 3, 4: 4, 5: 1, 6: 3, 7: 7, 8: 5, 9: 3, 10: 5, 11: 4, 12: 6, 13: 4, 14: 4}
{1: 5, 2: 6, 3: 6, 4: 7, 5: 4, 6: 3, 7: 7, 8: 6, 9: 3, 10: 6, 11: 7, 12: 7, 13: 5, 14: 4}
{1: 8, 2: 7, 3: 6, 4: 7, 5: 7, 6: 6, 7: 8, 8: 7, 9: 6, 10: 7, 11: 10, 12: 7, 13: 5, 14: 4}
{1: 9, 2: 10, 3: 9, 4: 7, 5: 7, 6: 9, 7: 8, 8: 7, 9: 6, 10: 10, 11: 10, 12: 8, 13: 8, 14: 7}
{1: 10, 2: 11, 3: 10, 4: 7, 5: 10, 6: 10, 7: 9, 8: 10, 9: 9, 10: 10, 11: 10, 12: 11, 13: 9, 14: 7}
{1: 13, 2: 11, 3: 11, 4: 8, 5: 11, 6: 11, 7: 10, 8: 11, 9: 9, 10: 11, 11: 13, 12: 11, 13: 10, 14: 10}
{1: 14, 2: 11, 3: 12, 4: 9, 5: 12, 6: 11,

C:\Users/PC/Documents/GitHub/Ugur-dynamic-scheduling/functions\weighted_days_model.py:168: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  l2 = pd.concat([l2, new_row1]).reset_index(drop=True)
C:\Users/PC/Documents/GitHub/Ugur-dynamic-scheduling/functions\weighted_days_model.py:183: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  d1_df = pd.concat([d1_df, new_row1]).reset_index(drop=True)
C:\Users/PC/Documents/GitHub/Ugur-dynamic-scheduling/functions\weighted_days_model.py:195: FutureWarning: The be

Set parameter Username
Academic license - for non-commercial use only - expires 2025-03-08
Read LP format model from file C:\Users\PC\AppData\Local\Temp\tmpkq66dwbv.pyomo.lp
Reading time = 0.06 seconds
x1: 8554 rows, 5915 columns, 137839 nonzeros
Set parameter TimeLimit to value 800
Gurobi Optimizer version 11.0.0 build v11.0.0rc2 (win64 - Windows 11+.0 (22631.2))

CPU model: 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz, instruction set [SSE2|AVX|AVX2|AVX512]
Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

Optimize a model with 8554 rows, 5915 columns and 137839 nonzeros
Model fingerprint: 0xa040fece
Variable types: 2366 continuous, 3549 integer (1183 binary)
Coefficient statistics:
  Matrix range     [1e+00, 1e+02]
  Objective range  [1e+00, 1e+00]
  Bounds range     [1e+00, 1e+00]
  RHS range        [1e+00, 1e+02]
Presolve removed 5005 rows and 364 columns
Presolve time: 0.33s
Presolved: 3549 rows, 5551 columns, 127692 nonzeros
Variable types: 0 continu

C:\Users/PC/Documents/GitHub/Ugur-dynamic-scheduling/functions\yeni_model.py:166: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  l2 = pd.concat([l2, new_row1.dropna()]).reset_index(drop=True)
C:\Users/PC/Documents/GitHub/Ugur-dynamic-scheduling/functions\yeni_model.py:182: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  d1_df = pd.concat([d1_df, new_row1]).reset_index(drop=True)
C:\Users/PC/Documents/GitHub/Ugur-dynamic-scheduling/functions\yeni_model.py:194: FutureWarning: The behavior of DataFram

"\npath = f'C:\\Users\\PC\\Documents\\GitHub\\Ugur-dynamic-scheduling\\wm_20teams_3000sec_sim_number{sim}.xlsx'\nwith pd.ExcelWriter(path, engine='xlsxwriter') as excel_writer:\n\n# Write each DataFrame to a different sheet\n    output.to_excel(excel_writer, sheet_name='wsolution', index=False)\n    l2.to_excel(excel_writer, sheet_name='weighted y+z ve d1+d2 degerleri', index=False)\n    data.to_excel(excel_writer, sheet_name='result matrix', index=False)\n    output2.to_excel(excel_writer, sheet_name='unw solution', index=False)\n    l22.to_excel(excel_writer, sheet_name='unw y+z ve d1+d2 degerleri', index=False)\n"

In [3]:
print(big_list_vizing)
print(big_list_canon) 
print(big_list_model)

[176.0]
[285.3333333333333]
[117.66666666666667]


In [4]:
print(simulation_canonical)
print(simulation_vizing)
print(simulation_model)
print(simulation_wm)
simulation_canonical = np.array(simulation_canonical)
simulation_vizing = np.array(simulation_vizing)
simulation_model = np.array(simulation_model)
simulation_wm = np.array(simulation_wm)
time_list = np.array(time_list)

print(np.mean(simulation_canonical))
print(np.mean(simulation_vizing))
print(np.mean(simulation_model))
print(np.mean(time_list))
print(np.mean(simulation_wm))
print(big_list_vizing)
print(big_list_canon)
print(big_list_model)

[292 302 262]
[163 196 169]
[113. 146.  99.]
[105 144 104]
285.3333333333333
176.0
119.33333333333333
805.6462619304657
117.66666666666667
[176.0]
[285.3333333333333]
[117.66666666666667]


In [5]:
df= pd.DataFrame({'Canonical': simulation_canonical, 'Vizing': simulation_vizing, 'Model': simulation_model, 'Weighted_Model': simulation_wm, 'model_time': time_list})

df.to_excel('C:/Users/PC/Documents/GitHub/Ugur-dynamic-scheduling/weighted_vs_unw_3simulation_14teams.xlsx', index = False)