In [5]:
import sys
sys.path.append('C:/Users/ug033207/dynamic scheduling/dynamic-scheduling/functions')
from point_rating import point_rating
from first_model import first_model
from yeni_model2 import yeni_model2
from first_round_rating import first_round_rating
from Elo_rating import Elo_rating
from generate_results import generate_results
from yeni_model import yeni_model
from first_round_model import first_round_model



import random
from pyomo.environ import *
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt
import time
import copy
import math

random.seed(1)

In [6]:
n = 10

teams = list(range(1,n+1))
days = list(range(1,n))

#results_df = pd.read_excel('C:/Users/ug033207/match_resultlar.xlsx', sheet_name= 'Spain first half')
results_df = generate_results(teams)
r = [1]
#Germany
#old_points = {1:77, 2:58, 3:69, 4:64, 5:11, 6:57, 7:55, 8:45, 9:42, 10:46, 11:52, 12:46, 13:33, 14:38, 15:42, 16:33, 17:28, 18:18}
old_points = {1:10, 2:8, 3:7, 4:5, 5:5, 6:1, 7:3, 8:15, 9:20, 10:1}
#old_points = {1:86, 2:73, 3:71, 4:59, 5:70, 6:65, 7:62, 8:55, 9:46, 10:48, 11:39, 12:47, 13:39, 14:42, 15:38, 16:42, 17:36, 18:42, 19:39, 20:31}

U_ij = np.zeros((n, n)) 
ratings_array = np.array(list(old_points.values()))


for i in range(n):
    for j in range(n):
        U_ij[i, j] = abs((ratings_array[i] - ratings_array[j]))

ratings_df = pd.DataFrame(U_ij, columns=teams, index=teams)
solution1, o = first_round_model(teams, days, ratings_df, r)

print(solution1)

Optimal solution found.
Team 2 vs Team 3 in Slot 1
Team 4 vs Team 5 in Slot 1
Team 6 vs Team 7 in Slot 1
Team 8 vs Team 1 in Slot 1
  Day Team 1 Team 2
0   1      2      3
1   1      4      5
2   1      6      7
3   1      8      1


In [7]:

result_array = np.zeros((n, n), dtype=int)

# Update the array based on your conditions
for _, row in results_df.iterrows():
    result = row['Result']
    team1 = row['Team 1']
    team2 = row['Team 2']

    index_team1 = teams.index(team1)
    index_team2 = teams.index(team2)

    if team1 == result:
        result_array[index_team1, index_team2] = 3
    elif team2 == result:
        result_array[index_team2, index_team1] = 3
    else:
        result_array[index_team1, index_team2] = 1
        result_array[index_team2, index_team1] = 1
print(result_array)
data = pd.DataFrame(result_array, columns=teams, index=teams)
#print(data)
output, obj_value = yeni_model2(teams, days, data, solution1)

[[0 3 1 3 0 3 0 0]
 [0 0 0 1 0 3 3 0]
 [1 3 0 3 0 0 1 3]
 [0 1 0 0 1 0 0 1]
 [3 3 3 1 0 3 1 3]
 [0 0 3 3 0 0 0 3]
 [3 0 1 3 1 3 0 3]
 [3 3 0 1 0 0 0 0]]
Optimal solution found.
Team 2 vs Team 3 in Slot 1
Team 4 vs Team 5 in Slot 1
Team 6 vs Team 7 in Slot 1
Team 8 vs Team 1 in Slot 1
Team 2 vs Team 7 in Slot 2
Team 3 vs Team 6 in Slot 2
Team 5 vs Team 1 in Slot 2
Team 8 vs Team 4 in Slot 2
Team 1 vs Team 4 in Slot 3
Team 2 vs Team 8 in Slot 3
Team 5 vs Team 6 in Slot 3
Team 7 vs Team 3 in Slot 3
Team 2 vs Team 6 in Slot 4
Team 3 vs Team 1 in Slot 4
Team 5 vs Team 8 in Slot 4
Team 7 vs Team 4 in Slot 4
Team 2 vs Team 5 in Slot 5
Team 4 vs Team 3 in Slot 5
Team 6 vs Team 1 in Slot 5
Team 7 vs Team 8 in Slot 5
Team 1 vs Team 2 in Slot 6
Team 3 vs Team 8 in Slot 6
Team 4 vs Team 6 in Slot 6
Team 7 vs Team 5 in Slot 6
Team 1 vs Team 7 in Slot 7
Team 4 vs Team 2 in Slot 7
Team 5 vs Team 3 in Slot 7
Team 8 vs Team 6 in Slot 7
2 vs 3 slot 1 y'nin değeri= 
{0.0}
4 vs 5 slot 1 y'nin değeri= 
{0.

In [9]:
print(obj_value)
print(sqrt(obj_value))
4913.999999999733

98.99999400000017
9.949874069554859


4913.999999999733