In [1]:
import sys
sys.path.append('C:/Users/ug033207/dynamic scheduling/dynamic-scheduling/functions')
from point_rating import point_rating
from first_model import first_model
from yeni_model2 import yeni_model2
from first_round_rating import first_round_rating
from Elo_rating import Elo_rating
from generate_results import generate_results
from yeni_model import yeni_model
from first_round_model import first_round_model



import random
from pyomo.environ import *
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt
import time
import copy
import math
random.seed(3)


In [2]:
n = 18

teams = list(range(1,n+1))
days = list(range(1,n))

results_df = pd.read_excel('C:/Users/ug033207/match_resultlar.xlsx', sheet_name= 'Germany first half')
#results_df = generate_results(teams)
#Germany
#old_points = {1:77, 2:58, 3:69, 4:64, 5:11, 6:57, 7:55, 8:45, 9:42, 10:46, 11:52, 12:46, 13:33, 14:38, 15:42, 16:33, 17:28, 18:18}
#old_points = {1:10, 2:8, 3:7, 4:5, 5:5, 6:1 ,7:12, 8:15} #
#old_points = {1:86, 2:73, 3:71, 4:59, 5:70, 6:65, 7:62, 8:55, 9:46, 10:48, 11:39, 12:47, 13:39, 14:42, 15:38, 16:42, 17:36, 18:42, 19:39, 20:31}



In [3]:

result_array = np.zeros((n, n), dtype=int)

# Update the array based on your conditions
for _, row in results_df.iterrows():
    result = row['Result']
    team1 = row['Team 1']
    team2 = row['Team 2']

    index_team1 = teams.index(team1)
    index_team2 = teams.index(team2)

    if team1 == result:
        result_array[index_team1, index_team2] = 3
    elif team2 == result:
        result_array[index_team2, index_team1] = 3
    else:
        result_array[index_team1, index_team2] = 1
        result_array[index_team2, index_team1] = 1
print(result_array)
data = pd.DataFrame(result_array, columns=teams, index=teams)
#print(data)
output, d1_df, d2_df, obj_value, l, l2 = yeni_model(teams, days, data)

[[0 1 1 3 3 1 3 1 3 3 1 3 1 0 3 3 3 3]
 [1 0 3 3 0 0 3 0 3 1 1 3 1 1 3 3 3 3]
 [1 0 0 3 3 0 3 0 0 3 0 3 3 3 3 3 0 3]
 [0 0 0 0 0 3 0 3 1 3 3 0 3 0 3 1 1 3]
 [0 3 0 3 0 3 1 3 0 1 1 3 3 3 0 1 3 3]
 [1 3 3 0 0 0 0 3 3 1 3 3 3 1 0 3 3 3]
 [0 0 0 3 1 3 0 1 0 3 3 1 3 3 3 1 3 3]
 [1 3 3 0 0 0 1 0 1 0 3 3 3 0 0 3 0 1]
 [0 0 3 1 3 0 3 1 0 3 0 3 3 1 3 3 1 1]
 [0 1 0 0 1 1 0 3 0 0 3 0 1 3 3 1 3 0]
 [1 1 3 0 1 0 0 0 3 0 0 1 1 3 1 0 3 3]
 [0 0 0 3 0 0 1 0 0 3 1 0 1 3 3 1 0 3]
 [1 1 0 0 0 0 0 0 0 1 1 1 0 3 3 3 1 1]
 [3 1 0 3 0 1 0 3 1 0 0 0 0 0 0 0 3 3]
 [0 0 0 0 3 3 0 3 0 0 1 0 0 3 0 3 0 0]
 [0 0 0 1 1 0 1 0 0 1 3 1 0 3 0 0 0 3]
 [0 0 3 1 0 0 0 3 1 0 0 3 1 0 3 3 0 3]
 [0 0 0 0 0 0 0 1 1 3 0 0 1 0 3 0 0 0]]


In [ ]:
print(output)
#output.to_excel('C:/Users/ug033207/solution.xlsx', sheet_name= 'Germany first half', index=False)
print(d1_df)
print(d2_df)


   Day Team 1 Team 2
0    1      1      4
1    1      3      5
2    1      6      2
3    2      3      1
4    2      4      2
5    2      6      5
6    3      1      5
7    3      2      3
8    3      6      4
9    4      1      6
10   4      2      5
11   4      3      4
12   5      2      1
13   5      4      5
14   5      6      3
   Day Team 1  Value
0    1      1    0.0
1    1      3    0.0
2    1      6    0.0
3    2      3    1.0
4    2      4    1.0
5    2      6    1.0
6    3      1    2.0
7    3      2    1.0
8    3      6    2.0
9    4      1    5.0
10   4      2    2.0
11   4      3    3.0
12   5      2    3.0
13   5      4    4.0
14   5      6    8.0
   Day Team 2  Value
0    1      4    0.0
1    1      5    0.0
2    1      2    0.0
3    2      1    1.0
4    2      2    1.0
5    2      5    1.0
6    3      5    2.0
7    3      3    2.0
8    3      4    4.0
9    4      6    5.0
10   4      5    2.0
11   4      4    4.0
12   5      1    5.0
13   5      5    3.0
14   5      3

In [ ]:
print(l)
print(sum(l))
print(l2)
print(sum(l2))

[0.0, 0.0, 0.0, 0.0, 0.0, 6.661338147750939e-16, 8.881784197001252e-16, 1.0000000000000382, 2.0, 8.881784197001252e-16, 4.440892098500626e-16, 1.0, 2.0, 1.0, 1.9999999999999991]
9.000000000000039
[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 2.0, 0.0, 0.0, 1.0, 2.0, 1.0, 2.0]
9.0


In [ ]:
print(obj_value)


15.000000000000073


In [ ]:
excel_writer = pd.ExcelWriter('C:/Users/ug033207/8 takim(mutlak model).xlsx', engine='xlsxwriter')

# Write each DataFrame to a different sheet
output.to_excel(excel_writer, sheet_name='solution', index=False)
d2_df.to_excel(excel_writer, sheet_name='d2', index=False)
d1_df.to_excel(excel_writer, sheet_name='d1', index=False)